import { useEffect, useState } from 'react';
import { Activity, Calendar, CheckCircle, Clock, Heart, Pill, Utensils } from 'lucide-react';
import { useAuth } from '../../context/AuthContext.jsx';

export default function ResidentDashboard() {
 const {user,api}=useAuth(); const id=user?._id; const [data,setData]=useState({tasks:[],appointments:[],medications:[],activities:[],menus:[]}); const [loading,setLoading]=useState(true);
 useEffect(()=>{if(!id)return; Promise.allSettled([api.get(`/tasks/${id}`),api.get(`/appointments/${id}`),api.get(`/medications/${id}`),api.get(`/activities/${id}`),api.get('/menus')]).then(r=>setData({tasks:r[0].status==='fulfilled'?r[0].value.data:[],appointments:r[1].status==='fulfilled'?r[1].value.data:[],medications:r[2].status==='fulfilled'?r[2].value.data:[],activities:r[3].status==='fulfilled'?r[3].value.data:[],menus:r[4].status==='fulfilled'?r[4].value.data:[]})).finally(()=>setLoading(false));},[api,id]);
 if(loading)return <div className="p-8 text-gray-500">Loading your dashboard...</div>;
 const task=data.tasks.find(t=>t.status!=='completed'&&t.status!=='cancelled'); const appt=data.appointments.find(a=>a.status==='scheduled'); const med=data.medications.find(m=>m.status==='active');
 return <div className="space-y-6 max-w-7xl mx-auto"><div className="card p-6 md:p-8 flex justify-between gap-4"><div><h1 className="text-2xl font-extrabold">Welcome, {user?.name || 'Resident'}.</h1><p className="text-gray-500 mt-1">Your dashboard shows information from your account.</p></div><Heart className="text-brand-600" size={36}/></div>
 <div className="grid md:grid-cols-3 gap-5"><Card title="Next Task" icon={CheckCircle} main={task?.title} sub={task?.description} extra={task?.scheduledAt?new Date(task.scheduledAt).toLocaleString():''}/><Card title="Next Appointment" icon={Calendar} main={appt?.doctorName||'No appointment'} sub={appt?.title} extra={appt?.location}/><Card title="Medication" icon={Pill} main={med?.name||'No active medication'} sub={med?.dosage} extra={med?.frequency}/></div>
 <div className="grid lg:grid-cols-2 gap-6"><div className="card p-6"><h3 className="text-lg font-bold mb-5">Recent Activities</h3>{data.activities.length===0?<Empty/>:<div className="space-y-4">{data.activities.slice(0,6).map(a=><div key={a._id} className="flex gap-3"><div className="w-9 h-9 rounded-full bg-brand-50 text-brand-600 flex items-center justify-center"><Activity size={16}/></div><div><p className="font-semibold text-sm">{a.title}</p><p className="text-sm text-gray-500">{a.description}</p><p className="text-xs text-gray-400 mt-1">{a.time||''}</p></div></div>)}</div>}</div>
 <div className="card p-6"><h3 className="text-lg font-bold mb-5 flex gap-2"><Utensils size={18}/> Menu</h3>{data.menus.length===0?<Empty text="No menu has been published yet."/>:<div className="space-y-3">{data.menus.slice(0,6).map(m=><div key={m._id} className="p-3 bg-gray-50 rounded-xl"><p className="font-semibold text-sm capitalize">{m.meal} · {m.day}</p><p className="text-sm text-gray-500">{m.items?.join(', ')}</p></div>)}</div>}</div></div></div>;
}
function Card({title,icon:Icon,main,sub,extra}){return <div className="card p-6"><div className="flex justify-between mb-4"><span className="badge bg-brand-50 text-brand-700 border border-brand-100">{title}</span><Icon size={20} className="text-gray-300"/></div><h3 className="text-xl font-bold">{main||'No data yet'}</h3><p className="text-sm text-gray-500 mt-1">{sub||'No information available.'}</p>{extra&&<p className="text-sm text-gray-600 mt-4 flex gap-2"><Clock size={15}/>{extra}</p>}</div>}
function Empty({text='No records are available yet.'}){return <p className="text-sm text-gray-400">{text}</p>}
